### PR TITLE
Fixing tests and supporting extension methods.

### LINKED ISSUE #17: Extension methods are not linked
Example: http://sourcebrowser.io/Browse/RaYell/Selenium.WebDriver.Extensions.Tests/WebDriverExtensionsTests.cs#65

### PR DESCRIPTION
**Pull request by JoshVarty**
Once merged this will close #17.

### CODE REVIEW

File: src/SourceBrowser.Generator/DocumentWalkers/DocumentWalker.cs [hunk 1]
```diff
@@ -169,6 +169,7 @@ public Token ProcessSymbolUsage(SyntaxToken token, ISymbol symbol, bool isDeclar
 
         private string GetSymbolName(ISymbol symbol)
         {
+            symbol = symbol.OriginalDefinition;
```
Comment (AmadeusW) [inline src/SourceBrowser.Generator/DocumentWalkers/DocumentWalker.cs]: What does it do and why do we need this?

File: src/SourceBrowser.Generator/DocumentWalkers/DocumentWalker.cs [hunk 2]
```diff
@@ -180,6 +181,18 @@ private string GetSymbolName(ISymbol symbol)
                 var containingName = symbol.ContainingSymbol.ToString();
                 fullyQualifiedName = containingName + _walkerUtils.LocalVariableDelimiter + symbol.Name;
             }
+            else if(symbol.Kind == SymbolKind.Method)
+            {
+                var methodSymbol = (IMethodSymbol)symbol;
+                if (methodSymbol.ReducedFrom != null)
+                {
+                    fullyQualifiedName = methodSymbol.ReducedFrom.ToString();
```
Comment (AmadeusW) [inline src/SourceBrowser.Generator/DocumentWalkers/DocumentWalker.cs]: Linking to extension methods is a difficult topic, and I think it warrants a comment here
